"""Generate the MONOLITH demo page (index.html) from the shipped binaries.

One self-contained page, no hand-edits: every claim it makes about the
font is read at generation time from fonts/MONOLITH-Variable.ttf (glyph
names, codepoints, advances, axis ranges) and from kerning.py's
KERN_PAIRS, then baked in as JSON. The page itself never embeds font
bytes — MONOLITH is resolved from the OS-installed font by family name,
so what a visitor sees is always their installed copy (the in-page
banner explains the Safari exception). Shaping is the browser's, the
same engine class as the HarfBuzz renders used everywhere else.

    uv run monolith-demo          # writes <repo>/index.html
"""

import argparse
import html
import json
from pathlib import Path
from typing import Any

from fontTools.ttLib import TTFont

from monolith.kerning import KERN_PAIRS
from monolith.specimen import build_rows

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_FONT = REPO_ROOT / "fonts" / "MONOLITH-Variable.ttf"
DEFAULT_OUT = REPO_ROOT / "index.html"
REPO_URL = "https://github.com/krfantasy/MONOLITH"
RELEASES_URL = REPO_URL + "/releases"
RELEASES_LATEST_URL = RELEASES_URL + "/latest"
KERN_SHOWN = 6  # strongest kern partners listed in the glyph popup
PARAGRAPH = (
    "NO CURVES. NO ROUND CORNERS. EVERY GLYPH IS A BLOCK. "
    "SPACE IS THE ONLY LUXURY, AND THE SPAC AXIS RATIONS IT BY THE UNIT."
)


def _esc_html(text: str) -> str:
    """HTML-escape and keep the output pure ASCII (numeric refs above 127)."""
    return html.escape(text).encode("ascii", "xmlcharrefreplace").decode("ascii")


def _js(name: str, data: Any) -> str:
    """One `const NAME = <json>;` line, safe to inline in a <script> tag."""
    blob = json.dumps(data, ensure_ascii=True, separators=(",", ":"))
    return "const %s = %s;" % (name, blob.replace("<", "\\u003c"))


def _char_map(cmap: dict[int, str]) -> dict[str, str]:
    """Every encoded char -> glyph name (a-z double-encodes to the caps)."""
    return {chr(cp): gname for cp, gname in sorted(cmap.items())}


def _glyph_entries(font: TTFont, cmap: dict[int, str]) -> list[dict[str, Any]]:
    """One popup record per distinct glyph, ordered by first codepoint."""
    hmtx = font["hmtx"]
    by_name: dict[str, list[int]] = {}
    for cp, gname in sorted(cmap.items()):
        by_name.setdefault(gname, []).append(cp)
    partners: dict[str, list[tuple[str, int, int]]] = {g: [] for g in by_name}
    for (lg, rg), v in KERN_PAIRS.items():
        if lg in partners:
            partners[lg].append((rg, v, 0))  # our glyph reads first: "AT"
        if rg in partners:
            partners[rg].append((lg, v, 1))  # partner reads first: "TA"
    entries: list[dict[str, Any]] = []
    for gname, cps in sorted(by_name.items(), key=lambda kv: kv[1][0]):
        strongest = sorted(partners[gname], key=lambda p: (-abs(p[1]), p[0]))[:KERN_SHOWN]
        entries.append(
            {
                "ch": chr(cps[0]),
                "cps": ["U+%04X" % cp for cp in cps],
                "name": gname,
                "adv": hmtx[gname][0],
                "kern": strongest,
            }
        )
    return entries


TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>MONOLITH - a brutalist extra-bold block font</title>
<meta name="description" content="MONOLITH: a modular, extra-bold, all-caps block font with SPAC and KERN variable axes. Free under the SIL Open Font License.">
<link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3E%3Crect width='16' height='16' fill='black'/%3E%3C/svg%3E">
<style>
/* No @font-face on purpose: MONOLITH is resolved from the OS-installed font
   (MONOLITH-Variable.ttf) by family name. A same-name @font-face would shadow
   the installed font, and its local() sources match inconsistently per browser;
   referencing the family directly has nothing to load - nothing can be blocked.
   (Safari additionally hides ALL installed third-party fonts from web content,
   so it cannot render MONOLITH at all; the banner below explains that.)
   Font bytes are never embedded in this file. It is generated by
   `uv run monolith-demo` from fonts/MONOLITH-Variable.ttf and kerning.py,
   which contribute metadata only: glyph names, codepoints, advances,
   kern partners, axis ranges. */
* { box-sizing: border-box; }
::selection { background: #000; color: #fff; }
body { margin: 0; background: #fff; color: #000; font: 15px/1.55 system-ui, sans-serif; }
.wrap { max-width: 1180px; margin: 0 auto; padding: 0 28px 72px; }
a { color: inherit; }
.mono { font-family: ui-monospace, Menlo, Consolas, monospace; }

/* hero */
header { border-bottom: 4px solid #000; padding: 52px 0 36px; }
.wordmark { font-family: MONOLITH, sans-serif; font-weight: 400; font-synthesis: none;
  font-size: clamp(64px, 13vw, 150px); line-height: .92; margin: 0 0 14px; }
.tagline { margin: 0 0 30px; text-transform: uppercase; letter-spacing: .16em; font-size: 14px; }
.btns { display: flex; gap: 16px; flex-wrap: wrap; margin: 0 0 16px; }
.btn { display: inline-block; border: 2px solid #000; background: #fff; color: #000;
  padding: 12px 22px; text-decoration: none; text-transform: uppercase; letter-spacing: .12em;
  font-weight: 700; font-size: 13px; box-shadow: 5px 5px 0 #000; }
.btn:hover, .btn:focus-visible { background: #000; color: #fff; }
.btn.ghost { box-shadow: none; font-weight: 400; }
.files { margin: 0; font-size: 12.5px; color: #555; }
#warn { display: none; background: #000; color: #fff; padding: 16px 20px; margin-top: 30px;
  font-size: 14px; line-height: 1.6; }
#warn code { background: #fff; color: #000; padding: 1px 6px; font-size: 13px; }

/* sections */
section { border-bottom: 4px solid #000; padding: 42px 0 54px; }
h2 { font-family: MONOLITH, sans-serif; font-weight: 400; font-synthesis: none;
  font-size: 24px; letter-spacing: .05em; margin: 0 0 6px; }
h2 .no { display: inline-block; border: 2px solid #000; font-size: 13px; letter-spacing: .1em;
  padding: 3px 9px; margin-right: 14px; vertical-align: 6px; }
.sub { color: #555; margin: 0 0 26px; }

/* 01 specimen */
.showcase { font-family: MONOLITH, sans-serif; font-weight: 400; font-synthesis: none;
  font-size: clamp(56px, 11vw, 128px); line-height: 1; margin: 0 0 30px; }
.rows { font-family: MONOLITH, sans-serif; font-weight: 400; font-synthesis: none;
  font-size: 30px; line-height: 1.45; }
.para { font-family: MONOLITH, sans-serif; font-weight: 400; font-synthesis: none;
  font-size: 19px; line-height: 1.7; max-width: 62ch; margin: 34px 0 0;
  border-top: 1px solid #000; padding-top: 26px; }

/* 02 glyph grid + popup */
#grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(64px, 1fr));
  border-top: 1px solid #000; border-left: 1px solid #000; cursor: crosshair; }
.cell { border-right: 1px solid #000; border-bottom: 1px solid #000; aspect-ratio: 1;
  display: flex; align-items: center; justify-content: center;
  font-family: MONOLITH, sans-serif; font-weight: 400; font-synthesis: none; font-size: 34px; }
.cell:hover, .cell:focus { background: #000; color: #fff; outline: none; }
#popup { position: fixed; display: none; z-index: 10; width: 300px; background: #fff;
  border: 2px solid #000; box-shadow: 8px 8px 0 #000; }
#popup.on { display: block; }
#popup .big { font-family: MONOLITH, sans-serif; font-weight: 400; font-synthesis: none;
  font-size: 104px; line-height: 1.1; text-align: center; border-bottom: 2px solid #000;
  padding: 20px 0 6px; min-height: 128px; }
#popup dl { margin: 0; padding: 14px 16px 12px; font-size: 12.5px; }
#popup dt { float: left; clear: left; width: 78px; padding-top: 2px; color: #555;
  text-transform: uppercase; letter-spacing: .1em; font-size: 11px; }
#popup dd { margin: 0 0 8px 86px; min-height: 14px; }
#popup .chips span { display: inline-block; border: 1px solid #000; padding: 0 6px;
  margin: 0 4px 4px 0; font-variant-numeric: tabular-nums; }

/* 03 axes */
.controls { display: flex; gap: 34px; flex-wrap: wrap; margin: 0 0 18px; }
.controls label { white-space: nowrap; }
input[type=range] { width: 260px; accent-color: #000; vertical-align: middle; }
.val { display: inline-block; min-width: 3ch; font-weight: 700; font-variant-numeric: tabular-nums; }
.hint { color: #777; font-size: 13px; }
#head { font-family: MONOLITH, sans-serif; font-weight: 400; font-synthesis: none;
  font-size: 72px; line-height: 1.08; border: 2px solid #000; padding: 14px 18px;
  min-height: 1.2em; white-space: pre-wrap; overflow-x: auto; outline: none; }
#head:focus { box-shadow: 6px 6px 0 #000; }
.readout { color: #555; margin: 14px 0 4px; }
.readout b, .chip b { color: #000; font-variant-numeric: tabular-nums; }
.chip { display: inline-block; border: 1px solid #000; padding: 1px 8px; margin: 3px 6px 3px 0;
  font-variant-numeric: tabular-nums; }
.none { color: #777; }
#measure { position: absolute; visibility: hidden; white-space: pre;
  font-family: MONOLITH, sans-serif; font-weight: 400; font-synthesis: none; font-size: 72px; }

/* footer */
footer { padding-top: 30px; font-size: 12.5px; color: #555; display: flex;
  justify-content: space-between; gap: 14px; flex-wrap: wrap; letter-spacing: .06em; }
</style>
</head>
<body>
<div class="wrap">
<header>
  <h1 class="wordmark">MONOLITH</h1>
  <p class="tagline">Modular. Extra-bold. Rectangular. White and black.</p>
  <div class="btns">
    <a class="btn" href="@@RELEASES_LATEST@@">Download - GitHub Releases</a>
    <a class="btn ghost" href="@@RELEASES@@">All releases</a>
  </div>
  <p class="files mono">MONOLITH-ExtraBold.ttf / .otf : the static block cut &middot;
    MONOLITH-Variable.ttf : SPAC (spacing) + KERN (kerning) axes</p>
  <div id="warn">MONOLITH isn't visible to this browser - everything on this page is a generic
    fallback font. Chrome / Edge / Firefox: install it -
    <code>cp fonts/MONOLITH-Variable.ttf ~/Library/Fonts/</code> (or double-click the file, then
    Install Font) - and reload; restart the browser if it was already running. Safari cannot work
    here at all: since Safari 12, WebKit hides every locally installed third-party font from web
    content (anti-fingerprinting), so use any other browser. This page deliberately never embeds
    the font - what it shows is always your installed copy.</div>
</header>

<section>
  <h2><span class="no">01</span>SPECIMEN</h2>
  <p class="sub">Shaped live by your browser from the installed font - the same engine class as
    the HarfBuzz renders used everywhere else in this repo.</p>
  <div class="showcase">MONOLITH</div>
  <div class="rows">@@ROWS@@</div>
  <p class="para">@@PARA@@</p>
</section>

<section>
  <h2><span class="no">02</span>GLYPHS</h2>
  <p class="sub">Every encoded character. Hover a cell - or tab to it - for the glyph's name,
    codepoints, advance width and strongest kern partners.</p>
  <div id="grid"></div>
</section>

<section>
  <h2><span class="no">03</span>AXES : SPAC + KERN</h2>
  <p class="sub">Type below. SPAC adds advance per glyph; KERN scales all @@NPAIRS@@ seam-metric
    kern pairs from none (0, the default) to full (100). They compose freely.</p>
  <div class="controls">
    <label>SPAC <input id="spac" type="range" min="@@SPAC_MIN@@" max="@@SPAC_MAX@@"
      value="@@SPAC_DEF@@" aria-label="SPAC axis">
      <span class="val" id="spacv">@@SPAC_DEF@@</span>
      <span class="hint">(0 block cut / 30 touching / 130 = ss01)</span></label>
    <label>KERN <input id="kern" type="range" min="@@KERN_MIN@@" max="@@KERN_MAX@@"
      value="@@KERN_DEF@@" aria-label="KERN axis">
      <span class="val" id="kernv">@@KERN_DEF@@</span>
      <span class="hint">(0 off, the default / 100 full)</span></label>
  </div>
  <div id="head" contenteditable="true" spellcheck="false">WAVE AVATAR TROUGH</div>
  <p class="readout">measured pull on the headline at KERN <b id="kv2">@@KERN_DEF@@</b>:
    <b id="pull">-</b></p>
  <div id="pairs"></div>
</section>

<footer>
  <span>FONT: SIL OPEN FONT LICENSE 1.1 / CODE: MIT</span>
  <span class="mono"><a href="@@REPO@@">GITHUB</a> / <a href="@@RELEASES@@">RELEASES</a> /
    GENERATED BY <code>monolith-demo</code></span>
</footer>
</div>

<div id="popup">
  <div class="big" id="p-big"></div>
  <dl>
    <dt>NAME</dt><dd class="mono" id="p-name"></dd>
    <dt>UNICODE</dt><dd class="mono" id="p-cp"></dd>
    <dt>ADVANCE</dt><dd class="mono" id="p-adv"></dd>
    <dt>KERN</dt><dd class="chips" id="p-kern"></dd>
  </dl>
</div>
<span id="measure"></span>
<script>
"use strict";
@@DATA@@

const $ = id => document.getElementById(id);
const esc = s => s.replace(/&/g, "&amp;").replace(/</g, "&lt;")
                  .replace(/>/g, "&gt;").replace(/"/g, "&quot;");
const NAME = {};
for (const g of GLYPHS) NAME[g.name] = g.ch === " " ? "\\u00a0" : g.ch;

// document.fonts.check() can't detect system fonts (WebKit returns true for
// anything), so probe by width: an installed MONOLITH measures differently
// from every generic family; a missing one collapses onto the sans fallback.
function monolithInstalled() {
  const probe = fam => {
    const s = document.createElement("span");
    s.style.cssText = "position:absolute;visibility:hidden;white-space:pre;"
                    + "font-weight:400;font-size:100px;font-family:" + fam;
    s.textContent = "mmmwwwiiilll@@00OO";
    document.body.appendChild(s);
    const w = s.offsetWidth;
    s.remove();
    return w;
  };
  const w = probe('"MONOLITH", sans-serif');
  return ["sans-serif", "serif", "monospace", "cursive"].every(f => probe(f) !== w);
}

// --- glyph grid + detail popup -----------------------------------------
const grid = $("grid"), popup = $("popup");
grid.innerHTML = GLYPHS.map((g, i) =>
  '<div class="cell" tabindex="0" data-i="' + i + '">'
  + (g.ch === " " ? "&nbsp;" : esc(g.ch)) + "</div>").join("");

function showPopup(i, cell) {
  const g = GLYPHS[i];
  $("p-big").textContent = g.ch === " " ? "\\u00a0" : g.ch;
  $("p-name").textContent = g.name;
  $("p-cp").textContent = g.cps.join("  ");
  $("p-adv").textContent = g.adv + " units / " + Math.round(g.adv * 100 / UPEM) + "% em";
  const chips = g.kern.map(k =>
    "<span><b>" + esc(k[2] ? NAME[k[0]] + g.ch : g.ch + NAME[k[0]]) + "</b> " + k[1] + "</span>"
  ).join("");
  $("p-kern").innerHTML = chips || '<span class="none">no kern partners</span>';
  popup.classList.add("on");
  const r = cell.getBoundingClientRect();
  const w = popup.offsetWidth, h = popup.offsetHeight;
  let x = r.right + 14;
  if (x + w > window.innerWidth - 12) x = Math.max(12, r.left - w - 14);
  const y = Math.min(Math.max(12, r.top), Math.max(12, window.innerHeight - h - 12));
  popup.style.left = x + "px";
  popup.style.top = y + "px";
}
function hidePopup() { popup.classList.remove("on"); }

grid.addEventListener("mouseover", e => {
  const c = e.target.closest(".cell");
  if (c) showPopup(+c.dataset.i, c);
});
grid.addEventListener("mouseout", e => {
  const c = e.target.closest(".cell");
  if (c && !c.contains(e.relatedTarget)) hidePopup();
});
grid.addEventListener("focusin", e => {
  const c = e.target.closest(".cell");
  if (c) showPopup(+c.dataset.i, c);
});
grid.addEventListener("focusout", e => {
  const c = e.target.closest(".cell");
  if (c && !c.contains(e.relatedTarget)) hidePopup();
});
document.addEventListener("keydown", e => { if (e.key === "Escape") hidePopup(); });

// --- SPAC + KERN playground --------------------------------------------
const head = $("head"), measure = $("measure");

function apply() {
  const spac = $("spac").value, kern = $("kern").value;
  $("spacv").textContent = spac;
  $("kernv").textContent = kern;
  $("kv2").textContent = kern;
  const fvs = '"SPAC" ' + spac + ', "KERN" ' + kern;
  head.style.fontVariationSettings = fvs;
  measure.style.fontVariationSettings = fvs;
  update();
}

function measuredWidth(fvs) {
  measure.style.fontVariationSettings = fvs;
  measure.textContent = head.innerText.replace(/\\n/g, " ");
  return measure.offsetWidth;
}

function update() {
  const text = head.innerText.replace(/\\n/g, " ");
  if (!text.trim()) { $("pull").textContent = "0 units (0 px)"; $("pairs").innerHTML = ""; return; }
  const k = +$("kern").value;
  const px = measuredWidth('"SPAC" ' + $("spac").value + ', "KERN" 0')
           - measuredWidth('"SPAC" ' + $("spac").value + ', "KERN" ' + k);
  const units = Math.round(px * UPEM / 72);  // 72 = #head / #measure font size in px
  $("pull").textContent = units + " units (" + px.toFixed(1) + " px @ 72px)";
  let out = "";
  for (let i = 0; i < text.length - 1; i++) {
    const n1 = CHAR[text[i]], n2 = CHAR[text[i + 1]];
    if (!n1 || !n2) continue;
    const v = KERN[n1 + " " + n2];
    if (v) out += '<span class="chip"><b>' + esc(text[i] + text[i + 1]) + "</b> "
               + Math.round(v * k / 100) + "</span>";
  }
  $("pairs").innerHTML = out || '<span class="none">no kerned pair in this text</span>';
}

$("warn").style.display = monolithInstalled() ? "none" : "block";
$("spac").addEventListener("input", apply);
$("kern").addEventListener("input", apply);
$("head").addEventListener("input", update);
apply();
</script>
</body>
</html>
"""


def build_html(font_path: str | Path = DEFAULT_FONT) -> str:
    """Render the demo page: binary metadata + kerning.py in, one HTML string out."""
    font = TTFont(str(font_path))
    cmap = font.getBestCmap()
    assert cmap is not None  # the VF ships a cmap; fail loudly if that regresses
    # fontTools table objects carry their fields at runtime, not in type stubs
    upem = int(font["head"].unitsPerEm)  # ty: ignore[unresolved-attribute]
    axes = {a.axisTag: a for a in font["fvar"].axes}
    spac, kern = axes["SPAC"], axes["KERN"]
    data = "\n".join(
        [
            _js("UPEM", upem),
            _js("CHAR", _char_map(cmap)),
            _js("KERN", {("%s %s" % pair): v for pair, v in sorted(KERN_PAIRS.items())}),
            _js("GLYPHS", _glyph_entries(font, cmap)),
        ]
    )
    rows = "\n".join('<div class="row">%s</div>' % _esc_html(r) for r in build_rows(cmap)[1:])
    page = TEMPLATE
    for token, value in (
        ("@@DATA@@", data),
        ("@@ROWS@@", rows),
        ("@@PARA@@", _esc_html(PARAGRAPH)),
        ("@@NPAIRS@@", str(len(KERN_PAIRS))),
        ("@@RELEASES@@", RELEASES_URL),
        ("@@RELEASES_LATEST@@", RELEASES_LATEST_URL),
        ("@@REPO@@", REPO_URL),
        ("@@SPAC_MIN@@", "%d" % spac.minValue),
        ("@@SPAC_MAX@@", "%d" % spac.maxValue),
        ("@@SPAC_DEF@@", "%d" % spac.defaultValue),
        ("@@KERN_MIN@@", "%d" % kern.minValue),
        ("@@KERN_MAX@@", "%d" % kern.maxValue),
        ("@@KERN_DEF@@", "%d" % kern.defaultValue),
    ):
        page = page.replace(token, value)
    return page


def main(argv: list[str] | None = None) -> None:
    ap = argparse.ArgumentParser(
        prog="monolith-demo",
        description="Generate the MONOLITH demo page (index.html) from the exported fonts.",
    )
    ap.add_argument(
        "--font", default=None, help="path to MONOLITH-Variable.ttf (default: <repo>/fonts/)"
    )
    ap.add_argument("--out", default=None, help="output HTML path (default: <repo>/index.html)")
    args = ap.parse_args(argv)
    font_path = Path(args.font) if args.font else DEFAULT_FONT
    out = Path(args.out) if args.out else DEFAULT_OUT
    if not font_path.exists():
        raise SystemExit(
            f"font not found: {font_path}\nBuild the fonts first (scripts/regen.sh, see README)."
        )
    out.write_text(build_html(font_path), encoding="utf-8")
    print("saved", out)
